apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: random-number
  annotations:
    description: 'Random number generator in Rust'
spec:
  components:
    - name: main
      type: component
      properties:
        image: wasmcloud-registry:5000/random_number:1
      traits:
        # Govern the spread/scheduling of the component
        - type: spreadscaler
          properties:
            instances: 1
